# Dockerfile.bot

FROM node:20

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos do bot
COPY package*.json ./
COPY index.cjs ./
COPY greetings.cjs ./
COPY utils.cjs ./
COPY tips_sobre_bot.cjs ./
#COPY auth_info_multi/ auth_info_multi/

# Instala dependências
RUN npm install

# Exponha a porta para possíveis webhooks (não obrigatório)
EXPOSE 8080

# Comando para iniciar o bot
CMD ["node", "index.cjs"]
