# Dockerfile.fastapi

FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos
COPY brasileirao_agent/ brasileirao_agent/
COPY fastapi_server/ fastapi_server/
COPY requirements.txt .
COPY .env .

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define a variável de ambiente
ENV PYTHONPATH=/app/brasileirao_agent/src

# Exponha a porta que a FastAPI vai rodar
EXPOSE 8000

# Comando para iniciar a API
CMD ["uvicorn", "fastapi_server.main:app", "--host", "0.0.0.0", "--port", "8000"]
