# Dockerfile.bot

FROM node:20

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos do bot
COPY package*.json ./
COPY index.cjs ./
COPY auth_info_multi/ auth_info_multi/

# Instala dependências
RUN npm install

# Exponha a porta para possíveis webhooks (não obrigatório)
EXPOSE 3000

# Comando para iniciar o bot
CMD ["node", "index.cjs"]
