// tips_sobre_bot.js
module.exports = [
  '⚡ Pergunte **“probabilidade Corinthians x Flamengo”** – eu calculo a chance de cada resultado com base nos números da temporada. 📊',
  '💡 Escreva **“Arrascaeta joga?”** – eu busco se ele está liberado, lesionado ou suspenso e trago a fonte oficial. 🏥',
  '📈 Digite **“estatísticas do Gabigol”** – receba gols, assistências, minutos por gol, cartões e média de notas. ⚽',
  '📰 Mande **“news Palmeiras”** – devolvo as manchetes mais recentes, data e se é informação confirmada ou rumor. 🗞️',
  '🧹 Se eu travar, use **“cancelar”** – limpo a fila na hora e fico pronto pra nova pergunta. 🔄',
  '🏆 Pergunte **“top 5 artilheiros”** – receba lista atualizada com gols e partidas jogadas. 🥅',
  '🚑 Use **“departamento médico do Botafogo”** – eu listo todos os lesionados e previsão de retorno. ⏳',
  '🚍 Digite **“fase do Bahia fora de casa”** – mostro pontos conquistados, saldo de gols e tendência fora da Fonte. 🌍',
  '🔎 Pergunte **“pontos fracos do Grêmio”** – analiso posição por posição onde o time costuma sofrer. ⚠️',
  '💰 Escreva **“finanças do Cruzeiro”** – informo valor de mercado do elenco e saldo das últimas janelas. 💸',
  '🎯 Mande **“quem lidera passes certos?”** – revelo o garçom do campeonato com números de precisão. 🎲',
  '🔥 Pergunte **“quem vem pressionado?”** – identifico times em má fase nas últimas 5 rodadas. 🔥',
  '🧤 Use **“melhores goleiros”** – entrego defesas difíceis, média de gols sofridos e jogos sem tomar gol. 🧱',
  '📆 Digite **“próximo jogo do Inter”** – devolvo data, local e forma recente dos dois times. 📅',
  '🟨 Pergunte **“cartões do Flamengo”** – informo quem está pendurado ou suspenso. 🟨🟥',
  '📊 Escreva **“aproveitamento do Fortaleza”** – mostro porcentagem em casa, fora e geral. 📈',
  '⚡ Mande **“viradas da rodada”** – destaco jogos que trocaram placar e momentos decisivos. 🔄',
  '🏦 Use **“net-spend Corinthians”** – resumo quanto o Timão gastou ou lucrou na última janela. 💵',
  '🎫 Pergunte **“lotação média do Grêmio”** – comparo presença de público na Arena em 2025. 🏟️',
  '🌍 Digite **“estrangeiros do Athletico-PR”** – mostro gringos do elenco e participação em jogos. 🌎',
  '⌚ Pergunte **“quem marca nos acréscimos?”** – revelo os especialistas em gols no apagar das luzes. ⌚',
  '🎯 Use **“finalizações certas do Santos”** – avalio pontaria do Peixe e taxa de conversão. 🎯',
  '📚 Lembrete rápido: comece com **“news”**, **“stats”**, **“probabilidade”** ou **“fase”** + nome do time para buscar qualquer tema. 📝',
  '⛑️ Escreva **“tempo de recuperação do Dudu”** – eu estimo a data de volta com base nas fontes médicas. ⏳',
  '🚧 Pergunte **“retranca do América-MG”** – mostro chutes concedidos, linhas defensivas e estilo tático. 🚌',
  '⚖️ Use **“fair play Corinthians”** – trago faltas cometidas e cartões por partida. ⚖️',
  '🐓 Digite **“zebras da rodada”** – aponto resultados surpreendentes que abalaram a rodada. 🐣',
  '🤜🤛 Pergunte **“comparar Paulinho x Hulk”** – coloco estatísticas lado a lado e explico quem leva vantagem. 📊',
  '⌛ Use **“decisivos no segundo tempo”** – listarei jogadores que viram jogo na etapa final. ⌛',
  '🏹 Escreva **“ataque do Palmeiras”** – combino gols marcados, chutes certos e eficácia da linha ofensiva. 🏹',
  '❄️ Pergunte **“quem tá sem vencer há 5 jogos?”** – exponho equipes em jejum de vitórias. ❄️',
  '📉 Use **“queda de rendimento Atlético-GO”** – analiso sequência negativa e principais números. 📉',
  '🗓️ Digite **“histórico Fla-Flu”** – trago vitórias, empates, tabus e artilheiros desse clássico. 📜',
  '➕➖ Pergunte **“saldo de gols Goiás”** – mostro balanço entre ataque e defesa esmeraldinos. 💚',
  '🎮 Use **“simula Vitória vs Cuiabá”** – gero prévia de resultado baseada na forma atual e confronto direto. 🎮',
  '⚠️ Digite **“alerta de lesão Fortaleza”** – eu checo se houve contusão de última hora antes do jogo. 🚑',
  '📅 Pergunte **“rodada 15 resumão”** – faço um recap dos jogos, destaques e viradas da rodada solicitada. 🗂️',
  '🔄 Use **“sequência do Corinthians”** – mostro os últimos 5 resultados e tendências de desempenho. 🔄',
  '🛡️ Escreva **“defesa menos vazada”** – aponto o time que sofre menos gols até agora. 🛡️',
  '🌟 Pergunte **“jogador da rodada”** – indico quem brilhou segundo estatísticas e impacto no resultado. 🏅',
  '📰 Use **“pressão no técnico do Vasco”** – cruzo sequência ruim, coletiva e rumores de bastidor. 🗣️',
  '🥅 Digite **“gols esperados contra Bahia”** – traduzo xG contra em linguagem de arquibancada. 🥅',
  '🌀 Pergunte **“posse de bola Fluminense”** – avalio se o toque-toque resulta em chances reais. ⚙️',
  '🔔 Use **“mudanças no elenco Goiás”** – trago chegadas, saídas e impacto financeiro. 🔄',
  '🧹 Digite **“limpar histórico”** – apago nossa conversa e começo do zero, sem perder sua sessão. 🧹',
  '🚀 Pergunte **“escanteios do Fluminense”** – apresento média de corners a favor e contra. 🚩',
  '🎹 Use **“passes certos Palmeiras”** – analiso controle de jogo do meio-campo alviverde. 🎹',
  '🔥 Digite **“quem tá voando?”** – listo jogadores em ascensão nas últimas 3 partidas. 🔥',
  '📈 Pergunte **“evolução do Cuiabá”** – mostro mudança na posição da tabela nas últimas rodadas. 📈',
  '🔁 Quer explorar mais? Basta escrever **“mais”** sempre que quiser outra dica – eu nunca repito a última. 😉',
  '🤝 Precisa de análise cruzada? Pergunte **“chama o senior analyst”** – eu aciono a equipe completa de especialistas e retorno um relatório resumido. 📑'
];
