// tips_sobre_bot.js
module.exports = [
    '⚡ *Dica rápida:* Pergunte “probabilidade Corinthians x Flamengo” e eu devolvo as chances de vitória! 🔮⚽',
    '💡 *Sabia?* Basta digitar “Arrascaeta joga?” que eu informo se ele está suspenso ou lesionado. 🏥',
    '📊 *Curioso?* Escreva “estatísticas do Gabigol” para ver gols, assistências e mais. 📈',
    '🗞️ *Atalho:* Comece com “news Palmeiras” e receba as manchetes mais quentes do Verdão! 🔥',
    '🔄 *Fila lotada?* Mande “cancelar” se eu estiver demorando pra responder e limpo tudo pra você.',
    '🏆 *Artilharia na veia:* Pergunte “top 5 artilheiros” e descubra quem tá com a chuteira quente. ⚽',
    '🚑 *De olho no DM:* “Departamento médico do Botafogo” lista todos os lesionados. 🩹',
    '📈 *Momento da equipe:* “Fase do Bahia fora de casa” mostra o aproveitamento longe da Fonte. 🌍',
    '🛠️ *Raio-X tático:* “Pontos fracos do Grêmio” destrincha posição por posição. 🔎',
    '💸 *Grana na mesa:* “Finanças do Cruzeiro” revela saldo de janela e valor de elenco. 💰',
    '🗣️ *Mesa redonda:* “Análise do Red Bull Bragantino” junta tática e finanças num pitaco só. 🎙️',
    '🔢 *Passe de qualidade:* “Quem lidera passes certos?” mostra o garçom do campeonato. 🎯',
    '🔥 *Pressão na área:* “Quem vem pressionado?” aponta times em crise nas últimas 5 partidas. 🔥',
    '🧤 *Paredão:* “Melhores goleiros” lista quem mais faz milagre debaixo das traves. 🧱',
    '📅 *Agenda:* “Próximo jogo do Inter” devolve data, adversário e contexto de forma. 📆',
    '💥 *Cartões à vista:* “Cartões do Flamengo” mostra quem tá pendurado. 🟨🟥',
    '🧮 *Aproveitamento:* “Aproveitamento do Fortaleza” traz porcentagem em casa, fora e geral. 📊',
    '🌪️ *Viradas épicas:* “Viradas da rodada” destaca jogos que pegaram fogo. 🔥',
    '🪙 *Net-spend:* “Net-spend Corinthians” entrega se o cofre tá pingando ou vazio. 🏦',
    '🏟️ *Torcida presente:* “Lotação média do Grêmio” mede a pressão na Arena. 🎫',
    '🌍 *Gringos no elenco:* “Estrangeiros do Athletico-PR” lista os gringos em campo. 🌎',
    '⏱️ *Gols no fim:* “Quem marca nos acréscimos?” revela os reis do abafa. ⌚',
    '🎯 *Precisão na finalização:* “Finalizações certas do Santos” mostra se o Peixe tá calibrado. 🎯',
    '📚 *Manual rápido:* Comece com “news”, “stats” ou “probabilidade” + nome do time — simples assim! 📝',
    '🤕 *Tempo de recuperação:* “Tempo de recuperação do Dudu” estima quando o craque volta. ⏳',
    '🚌 *Retranca braba:* “Retranca do América-MG” analisa se o Coelho estaciona o busão. 🚌',
    '⚖️ *Fair play:* “Fair play Corinthians” mostra faltas e cartões na conta. ⚖️',
    '🎲 *Zebra à vista:* “Quem é zebra na próxima rodada?” indica surpresa boa pra aposta. 🐓',
    '📊 *Comparativo:* “Comparar Paulinho x Hulk” põe os dois na balança métrica por métrica. ⚖️',
    '🧙 *Decisivos no 2º tempo:* “Quem decide no segundo tempo?” aponta viradores de jogo. ⌛',
    '🏹 *Eficiência de ataque:* “Ataque do Palmeiras” traduz dados em resenha fácil. 🏹',
    '🧊 *Geladeira:* “Quem tá sem vencer há 5 jogos?” evidencia quem esfriou na tabela. ❄️',
    '📈 *Tendência de queda:* “Queda de rendimento Atlético-GO” mostra sequência negativa. 📉',
    '🗓️ *Clássico histórico:* “Histórico Fla-Flu” traz vitórias, empates e tabus. 🗓️',
    '🧮 *Saldo de gols:* “Saldo de gols Goiás” avalia ataque e defesa do Verdão do Cerrado. ➕➖',
    '🎮 *Simulador rápido:* “Simula 1×1 Vitória vs Cuiabá” gera prévia baseada nos números atuais. 🎮',
    '🚨 *Alerta de lesão:* Pergunte de última hora e eu atualizo se alguém virou dúvida. 🚑',
    '🤔 *Odds de rebaixamento:* “Odds de rebaixamento do Vasco” mostra quem tá no sufoco. 📉',
    '🧪 *Sequência pesada:* “Teste de fogo pro Cuiabá” avalia confrontos complicados à vista. 🔥',
    '🏅 *Jogador da rodada:* “Quem foi o jogador da rodada?” aponta quem chamou a responsa. 🏅',
    '📰 *Rumores de técnico:* “Pressão no técnico do Vasco” cruza sequência ruim + rumores de demissão. 📰',
    '🥅 *Gols esperados contra:* “Gols esperados contra Bahia” vira papo de bar fácil, nada de planilha. 🥅',
    '📈 *Posse improdutiva:* “Posse de bola do Fluminense” explica se toca muito sem agredir. 🌀',
    '🔔 *Alertas de odds:* “Mudança de odds Corinthians” conta se a casa ajustou cotações. 🔔',
    '🧹 *Limpeza de fila:* Sempre que quiser acelerar, manda “cancelar” e recomeçamos do zero. 🧹',
    '🚀 *Bola parada:* “Escanteios do Fluminense” mostra força nas bolas alçadas. 🚀',
    '🎯 *Precisão de passes:* “Passes certos do Palmeiras” indica se o meio-campo tá afiado. 🎯',
    '🌡️ *Momento quente:* “Quem tá voando?” pergunta por jogadores em ascensão na última rodada. 🔥',
    '🔁 *Outra dica?* Só digitar “mais” e eu solto um truque novo toda vez. 😉',
    '🤝 *Chama reforço:* Se precisar de análise mais profunda, eu convoco os analistas de plantão! 🤝'
  ];
  